version: '3.8'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: your-email@example.com  # Use your actual email address
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
       - mynetwork

  user-service:
    image: keerthanaparsa/user-service:${TAG:-latest}
    expose:
      - "8050"
    depends_on:
      - kafka
    networks:
      - mynetwork

  marketplace-service:
    image: keerthanaparsa/marketplace-service:${TAG:-latest}
    expose:
      - "8070"
    depends_on:
      - kafka
    networks:
      - mynetwork

  event-service:
    image: keerthanaparsa/event-service:${TAG:-latest}
    expose:
      - "8060"
    depends_on:
      - kafka
    networks:
      - mynetwork

  frontend:
    image: keerthanaparsa/frontend:${TAG:-latest}
    expose:
      - "5173"
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
    networks:
      - mynetwork

  post-service:
    image: keerthanaparsa/post-service:${TAG:-latest}
    expose:
      - "8090"
    depends_on:
      - kafka
    networks:
      - mynetwork

  feed-service:
    image: keerthanaparsa/feed-service:${TAG:-latest}
    expose:
      - "8095"
    depends_on:
      - kafka
    networks:
      - mynetwork

  gateway-service:
    image: keerthanaparsa/gateway-service:${TAG:-latest}
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=sjsueconnect.me  # Replace with your actual domain
      - LETSENCRYPT_HOST=sjsueconnect.me  # Replace with your actual domain
      - LETSENCRYPT_EMAIL=keerthana.parsa@sjsu.edu # Replace with your email
    depends_on:
      - kafka
      - user-service
      - post-service
      - event-service
      - marketplace-service
      - feed-service
    networks:
      - mynetwork

  nginx-https:
    image: nginx:latest
    container_name: nginx-https
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway-service
    networks:
      - mynetwork

  kafka:
    image: apache/kafka-native:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: DOCKER://0.0.0.0:9093,HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:9093,HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mynetwork

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
