name: Build and Deploy to Railway

on:
  push:
    branches: [mv]  # Change to your main branch name if different (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tag
        id: tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # Build and push user-service
      - name: Build and push user-service
        uses: docker/build-push-action@v4
        with:
          context: ./UserService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ steps.tag.outputs.tag }}

      # Build and push marketplace-service
      - name: Build and push marketplace-service
        uses: docker/build-push-action@v4
        with:
          context: ./MarketplaceService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/marketplace-service:${{ steps.tag.outputs.tag }}

      # Build and push event-service
      - name: Build and push event-service
        uses: docker/build-push-action@v4
        with:
          context: ./EventService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-service:${{ steps.tag.outputs.tag }}

      # Build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.tag.outputs.tag }}

      # Build and push post-service
      - name: Build and push post-service
        uses: docker/build-push-action@v4
        with:
          context: ./PostService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/post-service:${{ steps.tag.outputs.tag }}

      # Build and push feed-service
      - name: Build and push feed-service
        uses: docker/build-push-action@v4
        with:
          context: ./FeedService
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:${{ steps.tag.outputs.tag }}